---
- name: Stop K3s safely
  hosts: all
  become: true
  tasks:
    - name: Try stopping k3s service
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: stopped
      with_items:
        - k3s
        - k3s-agent
      ignore_errors: yes

