---
- name: Stop K3s safely
  hosts: all
  become: true
  tasks:

    - name: Check if k3s service is active
      ansible.builtin.systemd:
        name: k3s
      register: k3s_status
      ignore_errors: yes
      changed_when: false

    - name: Stop K3s if running
      ansible.builtin.systemd:
        name: k3s
        state: stopped
        enabled: no
      when: k3s_status.status == "running"
      failed_when: false
